change log:add  breaking change to Remove the export of the Get package
Stacked-Org/stacked pull request #600
Opened 2022-05-06 15:50 UTC by eb-so

2022-05-06 17:28 UTC, ferrarafer reviewed
LGTM

2022-05-09 07:43 UTC, FilledStacks approved these changes

2022-05-09 07:46 UTC, FilledStacks requested changes
- Update the version to 0.8.21+1
- Add into Changelog 0.8.21+1 with text "Adds Breaking change indication below."
- Update Breaking Change to use ⚠️ emojis on both sides .i.e ⚠️ Break Change ⚠️

2022-05-09 11:06 UTC, FilledStacks approved these changes
Looks good!

2022-05-09 11:06 UTC, merged