Fix tests directories names
Stacked-Org/stacked pull request #604
Opened 2022-05-10 20:24 UTC by ferrarafer

Rename tests directories to avoid redundancy.

- Changed services tests directory from `test/services_tests` to `test/service`
- Changed viewmodels tests directory from `test/viewmodel_tests` to `test/viewmodel`
- Changed utils tests directory from `test/util_tests` to `test/util`
- Updated stacked_tools tests, example and playground to align with directory names changes

This PR closes #601, was messy 🙉

2022-05-11 13:13 UTC, Eimen2018 requested changes
Delete command would fail to get the right path... and i don't even know how you didn't see an error on delete_view_command.dart

2022-05-11 13:13 UTC, Eimen2018 commented on packages/stacked_tools/lib/src/templates/compiled_templates.dart
> -const String kViewTemplateGenericFolderPath = 'lib/ui/views/generic/';
@ferrarafer I added this for delete command i needed the folder path to remove the view and viewmodel

2022-05-13 07:33 UTC, FilledStacks commented
@ferrarafer I'm lost with this PR haha. I don't know if the changes I chatted to you about was applied. Send me a message on slack lets chat through it.

2022-05-15 09:40 UTC, FilledStacks commented
@ferrarafer we can close this? The config updates should include the general fix for this problem.

2022-05-16 13:02 UTC, ferrarafer commented
> @ferrarafer we can close this? The config updates should include the general fix for this problem.

Sure.

2022-05-16 13:02 UTC, closed without merging