Feature/add custom text editing controller to form field
Stacked-Org/stacked pull request #668
Opened 2022-06-14 08:17 UTC by eb-so

2022-06-14 09:36 UTC, Eimen2018 approved these changes
A lot of refactor...LGTM

2022-06-14 09:55 UTC, eb-so commented
> A lot of refactor...LGTM

Correct, also I think we should cover the form generator with more unit tests, cause we are going to add a lot of new features in the future

2022-06-15 06:59 UTC, FilledStacks requested changes
Some naming changes we have to apply to make things clearer in the code. 

This PR sets us up to confirm the order of calls for a builder as well, which will allow us to know if anything changes in order or output. 

There's a clear way to make this unit testable, it'll just take time and I don't know how to explain it in words haha.

2022-06-15 06:59 UTC, FilledStacks commented on packages/stacked_generator/lib/src/generators/forms/stacked_form_content_generator.dart
> +    final formGeneratorUtil = FormGeneratorUtil(formViewConfig: _formViewConfig)
Given that this is now using the builder pattern I think this should be named `FormBuilder`

2022-06-15 06:59 UTC, FilledStacks commented on packages/stacked_generator/lib/src/generators/forms/stacked_form_content_generator.dart
> +      ..generateTextEditingControllersForTextFields()
All `generate` commands should change to `add` to make sense in the domain language we're building in stacked.

2022-06-15 07:30 UTC, merged