Fix Sign In with phone number
Stacked-Org/stacked pull request #677
Opened 2022-06-24 02:17 UTC by ferrarafer

The purpose of this PR is to  remove sign in with phone number methods that should be used for Web Platform and add methods for Native Platform.

Also, `FirebaseAuthException` is exported to avoid firebase_auth dependency when using stacked_firebase_auth.

## Reference
The Firebase Authentication SDK for Flutter provides two individual ways to sign a user in with their phone number. Native (e.g. Android & iOS) platforms provide different functionality to validating a phone number than the web, therefore two methods exist for each platform exclusively:

Native Platform: verifyPhoneNumber.
Web Platform: signInWithPhoneNumber.

Reference: [link](https://firebase.google.com/docs/auth/flutter/phone-auth)

2022-06-24 09:29 UTC, eb-so commented
LGTM, as long as it still works for the web

2022-06-24 11:54 UTC, ferrarafer commented
> LGTM, as long as it still works for the web

What do you mean? Are we using Stacked on web browsers? If that is the case, I can expose also Web Platform methods.

2022-06-24 12:16 UTC, Eimen2018 commented
@ferrarafer We need the web too we are currently working on web 😂

2022-06-24 12:35 UTC, ferrarafer commented
> @ferrarafer We need the web too we are currently working on web 😂

@Eimen2018 Oki dokie, I will put back those methods for web in a few minutes.

2022-06-24 12:37 UTC, eb-so commented
@ferrarafer Beware web devs in the house

2022-06-24 12:40 UTC, ferrarafer commented
> @ferrarafer Beware web devs in the house

@eb-so haha my mistake, sorry. Web Platform support added back.

2022-06-27 06:58 UTC, FilledStacks requested changes
We only need the change log updates to match what has been changed then this is ready to be merged.

2022-06-27 06:58 UTC, FilledStacks commented on packages/stacked_firebase_auth/CHANGELOG.md
> +- Remove signInWithPhoneNumber (implements Web Platform)
This has not been removed? Can we update the changelog to match the latest hanges please

2022-06-27 11:15 UTC, FilledStacks approved these changes

2022-06-27 11:15 UTC, merged