Feat/stacked refactor
Stacked-Org/stacked pull request #712
Opened 2022-08-06 14:23 UTC by eb-so

- Refactor `BaseViewModel` by extracting the different functionalities to mixins.
- Remove the inconsistency between the `BaseViewModel` and `FutureViewModel`, `StreamViewModel` when setting the error, data values.
- Now we have three mixins that can be mix with any viewmodel and they are:
  - `FutureRunnerHelper` that has `runBusyFuture` and `runErrorFuture` functions
  - `MessageStateHelper` that adds message proberty to the viewmodel
  - `DataStateHelper` that adds data proberty to the viewmodel

2022-08-08 11:07 UTC, FilledStacks approved these changes
This is great. I like the idea, but now there are going to be things we have to re-teach. 

I'd like the idea of a "Future functionality", "Stream Functionality" and "Reactive Functionality" to still exist. 

The refactor is good, but currently won't be easy to teach or be usable for the reason of the refactor. 

As long as everything developer facing stays the same I'm happy 🚀

2022-08-21 15:02 UTC, FilledStacks requested changes
The big request is to not remove old viewmodels until we've properly allowed users to learn about the composable functionality and choose if they want to use that. For instance, the views that are using IndexTrackingViewModel I don't want to update if I move up a version. But when I want to use multiple sets of functionalities like Future and Index then I can use the composable mixins. 

When we can avoid breaking changes we should. We have to think about the impact this would have on teams that need to release next week and suddenly has to go through and update all their code with nothing in the docs that tells them how to do it. 

So the changes requested in this review is:
- Ensure we still have all previous types available and working the same way
- The new types should be completely empty and use the new mixin functionality (This allows us to see if it works as expected before telling everyone to start using it)
- This should be a release that goes into the 0.8.0 beta so that we can test it out in venu first before it's released into the world. 

It'll allow me to catch all breaking changes before it goes out so that we can ensure we're making a stable release.

2022-08-21 15:02 UTC, FilledStacks commented on packages/stacked/lib/src/state_management/helpers/index_tracking_state_helper.dart
> +mixin IndexTrackingStateHelper on ChangeNotifier {
Instead of this breaking change we can keep the viewmodels and make use the new mixin. This way no one's code will break when they updated but we can then write a tutorial or a blog post about the composable functionalites and explain how it can be used.

2022-09-06 08:30 UTC, FilledStacks commented
@eb-so am I right in saying that this is all in the beta branch and will be merged when master is merged? Would like to close this.

2022-09-06 11:21 UTC, eb-so commented
Yes you are correct

> On 6 Sep 2022, at 11:30 AM, Dane Mackier ***@***.***> wrote:
> 
> 
> @eb-so <https://github.com/eb-so> am I right in saying that this is all in the beta branch and will be merged when master is merged? Would like to close this.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/FilledStacks/stacked/pull/712#issuecomment-1237829075>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AVHUEA6TYAMPSCMVVFAQUMDV436LPANCNFSM55YVDHLQ>.
> You are receiving this because you were mentioned.
>

2022-09-07 06:33 UTC, closed without merging

2023-07-26 02:43 UTC, VittorioParagallo commented
Autogenerated form code doesn't work for FormStateHelper.

In my use case I have a ViewModel like: 
`class MemberDetailsViewModel extends MultipleStreamViewModel with FormStateHelper{}`

And In the View:
  `@override
  void onViewModelReady(MemberDetailsViewModel viewModel) => syncFormWithViewModel(viewModel);`

But **syncFormWithViewModel autogenerated in the form file expects FormViewModel**. 
So to make it work i manually change the types in the autogenerated "member_details_view.form.dart"  (FormViewModel -> FormStateHelper)

I think is related to the first  @eb-so wrote in chronology
> Note: this change needs one small change in the form generator which is replace FormViewModel with FormStateHelper.

I just wanted to ask if it is a problem and there is a fix planned or I'm suppose to find another way?
Thanks a lot