Support for Duration in SnackbarConfig
Stacked-Org/stacked pull request #727
Opened 2022-08-24 15:10 UTC by vishhmakasana

Duration field added in snackbar_config.dart so that we will not have to specify Duration on each show snackbar call.

2022-08-31 10:39 UTC, Eimen2018 requested changes
LGTM, please update the comment and add package maintenance (increase version and update change log)

2022-08-31 10:39 UTC, Eimen2018 commented on packages/stacked_services/lib/src/snackbar/snackbar_service.dart
> +      // messageText: snackbarConfig.messageColor != null || message.isNotEmpty
Yes i think it should be snackbarConfig.messageColor

2023-04-10 10:55 UTC, FilledStacks approved these changes
Thanks for the PR and Thanks @Eimen2018 for the review.

We have an automatic deploy and update of changelog and version now 😄

2023-04-10 10:56 UTC, FilledStacks requested changes
Only request is to fix merge issues and then we can move forward

2023-04-10 11:56 UTC, closed without merging