update README to use recommended approach for reactiveServices
Stacked-Org/stacked pull request #736
Opened 2022-10-03 17:49 UTC by dvagala

In the readme, there was no mention of the correct usage of the reactiveServices. I removed the old approach with ReactiveValues altogether, I've just written there a little side note. Let me know if you think the old approach should take space in the readme.

[Stacked slack conversation about this.](https://filledstacks.slack.com/archives/CJY4SV5KQ/p1664583320808749)

2022-10-04 07:43 UTC, FilledStacks requested changes
Awesome! Thank you for the update. Just comments for changes. In addition to those comments you should also:

- Update the version of stacked in the pubspec to match the changelog.md entry.

2022-10-04 07:43 UTC, FilledStacks commented on packages/stacked/README.md
> +class PostsReactiveService with ReactiveServiceMixin {
Please remove Reactive from the name. That's not a pattern that I think we should teach

2022-10-04 07:43 UTC, FilledStacks commented on packages/stacked/README.md
> +In the stacked library, we have a `ReactiveServiceMixin` which can be used to store a state that is needed across multiple ViewModels. The approch is simple. Just set the state variable and call `not
approch -> approach

2022-10-04 07:43 UTC, FilledStacks commented on packages/stacked/README.md
> +  final _postsReactiveService = locator<PostsReactiveService>();
Update these as well to remove `Reactive` from the name

2022-10-04 12:53 UTC, dvagala commented
@FilledStacks thanks, I've corrected those issues

2022-10-05 03:04 UTC, FilledStacks approved these changes
Awesome!! Merging in now

2022-10-05 03:05 UTC, FilledStacks commented
I'll have to fix this PR before I can merge it in. I'll see if I can find some time for it in the week after my releases are out.

2022-10-28 12:46 UTC, FilledStacks approved these changes
Gonna merge this the CI is breaking for a weird reason.

2022-10-28 12:46 UTC, merged