Stacked improvements
Stacked-Org/stacked pull request #771
Opened 2022-11-20 16:13 UTC by ferrarafer

- Added ListenableServiceMixin
- Deprecated ReactiveServiceMixin
- Use ListenableServiceMixin instead of ReactiveServiceMixin
- Change reactiveServices property name on ReactiveViewModels to listenableServices
- Move data models to data_models folder
- Move SkeletonLoader to ui folder
- Rename state_management folder to view_models
- Fix unit test file names to follow conventions

2022-11-20 16:23 UTC, ferrarafer commented
@FilledStacks 
We need to verify how to extends `ReactiveServiceMixin` from `ListenableServiceMixin`.

2022-11-30 02:59 UTC, FilledStacks requested changes
Great work! 

We should add a 

### Breaking Changes

Section into the Change log so we can easily identify them and add it to our migration guide when we do our release.

2022-11-30 02:59 UTC, FilledStacks commented on packages/stacked/example/lib/ui/builder_widget_example/builder_widget_example_view.dart
> +class BuilderWidgetExampleView extends StackedView<HomeViewModel> {
Nice 🚀 We should note this down as a breaking change please. 

It needs to go into our migration section.

2022-12-01 04:48 UTC, FilledStacks approved these changes
Happy with this. As a note the Breaking Changes title should be an H3 Using `###`

2022-12-01 04:48 UTC, merged