Add the posibility to add the platform and an organization
Stacked-Org/stacked pull request #893
Opened 2023-03-11 22:11 UTC by felixkriechbaum

Hello all,

regarding the following FR which I mentioned the other day (#874) I thought I'd try my hand at it and created something that does what I mentioned.

There are 2 new "arguments" that you can now specify when creating a stacked app.

This would be -o / --org followed by the bundle identifier
```shell
-o com.filledstack 
```
or
```shell
--org com.filledstack
```

and the same for the platform but with -p --platform followed by the platforms separated by ,
 
```shell
-p windows,linux 
```
or
```shell
--platform windows,linux)
 ```

I have tested it as far as possible, but of course strange or untested things can always happen

Please be merciful with me, it's my first PR :D
For questions or improvement wishes I am gladly open

2023-03-13 03:46 UTC, FilledStacks requested changes
Hi, thanks for the PR. 

1. You should test your code before you make changes and after you've made changes (this doesn't work)
2. If you don't know how to test your code you should spend all your time figuring that out first before you write the code. Submitting code that doesn't work hands over responsibility you took on to the code reviewer
3. If your code doesn't work your work is not done
4. Follow coding principles that I teach in my videos + the basic software engineering principles like keeping code DRY
5. When you see conventions in a codebase try and follow those. The thing you want to do, unless a completely new feature, would have something similar in the code you can follow. In this case there are many commands that take options. You should follow those commands implementations. 

The biggest take away is that you don't know if your code works (It doesn't), and you should rather spend time figuring out to test it because there's a lot you didn't implement here. 

- Templates are not updated and compiled into the cli
- Template rendering is not updated (writing your value into the template)

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/commands/create/create_app_command.dart
> +    _cLog.stackedOutput(message: argResults!.rest.first, isBold: true);
Please remove this log. It looks like it was used for debugging.

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/constants/command_constants.dart
> +const String ksOrganization = "--org";
This is the only constant used in the command line that has -- in front of it. Please follow the convention of the rest of the option implementations. Look at template for reference.

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/commands/create/create_app_command.dart
> +    }
- The code has to be DRY (Don't Repeat Code). You have multiple lines of the exact same code in a row, 4 times in a row. 
- None of the other commands use this convention you're using to check if an option was supplied. Please make sure you understand how the other commands to it and use the same way. 
- No Magic values in our code unless there's an explicit instruction that it has to be generated in the future from the compile command. Please remove all magic values
- You don't have to check the option for both versions, again, look at the implementation of the other options. Follow along with the one that closes resemble what you want to implement and copy the structure and implementation of that.

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/commands/create/create_app_command.dart
> +    }
This check can be refactored out of here and unit tested on its own.

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/commands/create/create_app_command.dart
> +    }
This check should be refactored out of there and unit tested

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/services/process_service.dart
> +    }
This pattern is causing a lot of additional code that's not required. you can simply make the value null and use null to know if a value was added or not. Making it required and passing empty is not a good pattern.

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/services/process_service.dart
> +    arguments.add(appName);
This can all be done in line in the array definition using the latest dart syntax. 

```dart
[
 if(..)
  value,
value,
]
```

2023-03-13 03:46 UTC, FilledStacks commented on packages/stacked_cli/lib/src/commands/create/create_app_command.dart
> +      "org",
Please remove these string literals and follow the pattern of the other options.

2023-05-16 11:59 UTC, closed without merging

2023-05-16 12:00 UTC, felixkriechbaum commented
Will take a look and reopen when finished